//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPatitentRegApp.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedDbEntities : DbContext
    {
        public MedDbEntities()
            : base("name=MedDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<D_Category> D_Category { get; set; }
        public virtual DbSet<D_ChangeType> D_ChangeType { get; set; }
        public virtual DbSet<D_Diagnosis> D_Diagnosis { get; set; }
        public virtual DbSet<D_Doctor> D_Doctor { get; set; }
        public virtual DbSet<D_DoctorGroup> D_DoctorGroup { get; set; }
        public virtual DbSet<D_DoctorWorkSchedule> D_DoctorWorkSchedule { get; set; }
        public virtual DbSet<D_DoctorWorkSchedule_History> D_DoctorWorkSchedule_History { get; set; }
        public virtual DbSet<D_Gender> D_Gender { get; set; }
        public virtual DbSet<D_HistoryDiagnosis> D_HistoryDiagnosis { get; set; }
        public virtual DbSet<D_HospitalBedFund> D_HospitalBedFund { get; set; }
        public virtual DbSet<D_Patient> D_Patient { get; set; }
        public virtual DbSet<D_ReceptionSchedule> D_ReceptionSchedule { get; set; }
        public virtual DbSet<D_Role> D_Role { get; set; }
        public virtual DbSet<D_User> D_User { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TherapeuticPatient> TherapeuticPatients { get; set; }
    }
}
