//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPatitentRegApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_DoctorWorkSchedule
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan TimeBeginDay { get; set; }
        public System.TimeSpan TimeEndDay { get; set; }
        public Nullable<bool> isWorked { get; set; }
        public int DoctorId { get; set; }
        public Nullable<bool> isApproved { get; set; }
    
        public virtual D_Doctor D_Doctor { get; set; }
    }
}
