//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPatitentRegApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public D_Patient()
        {
            this.D_HistoryDiagnosis = new HashSet<D_HistoryDiagnosis>();
            this.D_HospitalBedFund = new HashSet<D_HospitalBedFund>();
            this.D_ReceptionSchedule = new HashSet<D_ReceptionSchedule>();
            this.TherapeuticPatients = new HashSet<TherapeuticPatient>();
        }
    
        public int Id { get; set; }
        public string Photo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SecondName { get; set; }
        public string Passport { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Medcard { get; set; }
        public Nullable<System.DateTime> MedcardDate { get; set; }
        public Nullable<System.DateTime> LastVizitDate { get; set; }
        public Nullable<System.DateTime> VizitDate { get; set; }
        public string InsPolicy { get; set; }
        public Nullable<System.DateTime> InsPolicyDate { get; set; }
    
        public virtual D_Gender D_Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_HistoryDiagnosis> D_HistoryDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_HospitalBedFund> D_HospitalBedFund { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_ReceptionSchedule> D_ReceptionSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapeuticPatient> TherapeuticPatients { get; set; }
    }
}
