//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalAdministration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public D_Doctor()
        {
            this.D_DoctorGroup = new HashSet<D_DoctorGroup>();
            this.D_DoctorWorkSchedule = new HashSet<D_DoctorWorkSchedule>();
            this.D_DoctorWorkSchedule_History = new HashSet<D_DoctorWorkSchedule_History>();
            this.TherapeuticPatients = new HashSet<TherapeuticPatient>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SecondName { get; set; }
        public Nullable<int> Category { get; set; }
    
        public virtual D_Category D_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_DoctorGroup> D_DoctorGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_DoctorWorkSchedule> D_DoctorWorkSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_DoctorWorkSchedule_History> D_DoctorWorkSchedule_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapeuticPatient> TherapeuticPatients { get; set; }
    }
}
